name: Tests

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 4.7.2
      - name: Restore Dependencies
        run: dotnet restore ./MostAwesomeDartApplicationEver/MostAwesomeDartApplicationEver.sln
      - name: Build
        run: dotnet build ./MostAwesomeDartApplicationEver/MostAwesomeDartApplicationEver.sln
      - name: Unit Tests
        run: dotnet test ./MostAwesomeDartApplicationEver/MostAwesomeDartApplicationEver.sln
