name: Tests

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore Dependencies
        run: dotnet restore ./MostAwesomeDartApplicationEver/
        
      - name: Build
        run: dotnet build --no-restore ./MostAwesomeDartApplicationEver/
        
      - name: Test
        run: dotnet test --no-build --verbosity minimal ./MostAwesomeDartApplicationEver/ --logger "trx;LogFileName=test-results.trx" || true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
