name: Tests

on: push

jobs:
  run-tests:
    name: Unit testing
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Dependencies
        run: dotnet restore ./MostAwesomeDartApplicationEver/MostAwesomeDartApplicationEver.sln
      - name: Build
        run: dotnet build ./MostAwesomeDartApplicationEver/MostAwesomeDartApplicationEver.sln
      - name: Unit Tests
        run: dotnet test ./MostAwesomeDartApplicationEver/MostAwesomeDartApplicationEver.sln
